[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
catppuccin = "2.6.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
strum = "0.27.2"
tui-piechart = "0.3.1"
